fix(web): obtain media device label
binbat/woom pull request #10
Opened 2024-10-21 12:48 UTC by WinterJack002

Fix the issue where Firefox browser device list cannot be read.

2024-10-21 12:52 UTC, WinterJack002 commented
Fix the issue where Firefox browser device list cannot be read, replace 'label' with 'kind+DeviceId'.

2024-10-21 14:00 UTC, a-wing requested changes
1. Use English comment. please
2. Remove unless line
3. Remove unless and debug `console.log`
4. Code style

* * *
About code style:

http://www.ruanyifeng.com/blog/2012/04/javascript_programming_style.html
https://www.cnblogs.com/Yellow-ice/p/15127392.html

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +// 1.将每个设备的 deviceId 和 label 转换为可显示的格式。如果 label 为空，会使用设备类型和 deviceId 作为显示名称。
Use English comment. please

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +// 2.uniqByValue 去重
English comment

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +      if (status.name === "audio_capture" || "microphone") { // "microphone"作为string不一直为ture吗？
`(status.name === "audio_capture" || status.name === "microphone")`

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +    console.log('this is audios:',audios)
Remove this line

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +    //const videos: Device[] = devices.filter(i => i.kind === 'videoinput')
Remove

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +  console.log('this is uniqueAudios:',uniqueAudios)
Remove this line

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +    }else{
`} else {`

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +  }
Trim tail ` `

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +        //await setCurrentDeviceAudio(device.value)
Remove unless line

2024-10-21 14:00 UTC, a-wing commented on webapp/components/device.tsx
> +        console.log('Video device set successfully')
```javascript
        try {
          await setCurrentDeviceVideo(device.value)
```

2024-10-22 04:30 UTC, a-wing commented
BTW: CLA. please. https://github.com/binbat/live777/blob/main/.github/CLA.md#list-of-contributors

You can read this example: https://github.com/binbat/live777/pull/95

2024-10-25 18:59 UTC, WinterJack002 commented
I do have configured the PGP key and signed it. However, the email address in my Git configuration is not the one for GPG signing (bound to GitHub). I just changed it with` git config --global user.email`. The next time I submit, it should show that it is verified.

2024-10-26 00:35 UTC, a-wing requested changes
But, this patch has some problem is no resolve

This is use this patch is firefox:

<img width="1485" alt="Screenshot 2024-10-26 at 08 33 14" src="https://github.com/user-attachments/assets/da31966f-c30b-4b17-9454-3c06fe398570">

* * *

But this is live777 debugger show device in firefox

<img width="903" alt="Screenshot 2024-10-26 at 08 32 49" src="https://github.com/user-attachments/assets/03012407-ef30-47ab-9051-cf4e3e006585">

2024-10-26 00:35 UTC, a-wing commented on webapp/components/device.tsx
> +
This blank line is unused

2024-10-26 00:35 UTC, a-wing commented on webapp/components/device.tsx
> +        {
`if (device) {`

2024-10-26 00:35 UTC, a-wing commented on webapp/components/device.tsx
> +          console.log('Audio device set successfully')
Remove this log

2024-10-26 00:35 UTC, a-wing commented on webapp/components/device.tsx
> +        console.log('Video device set successfully')
Remove this successfully log

2024-10-26 00:35 UTC, a-wing commented on webapp/components/device.tsx
> +    }
This block indent style error

2024-10-26 00:35 UTC, a-wing commented on webapp/components/device.tsx
> +    setDeviceVideo(convertToDevice(uniqueVideos,'videoinput'))
`convertToDevice(uniqueVideos, 'videoinput')`

`,` after add a ` `

2024-10-26 00:46 UTC, a-wing commented
https://github.com/binbat/live777/commit/1fa54d423b5b6f53c15c1dbca2613005bd79b3f2#diff-a79fe0a1bc4d37db7cc13373925f80b8c81b4bb2ec609d32fb27d83d6c15c875R93-R96

2024-11-04 10:15 UTC, WinterJack002 commented
Correct the coding format and update issue solution.

2024-11-05 12:24 UTC, merged